### PR TITLE
Remove deprecation warnings in php 8.2

### PR DESCRIPTION
**Pull request by AlexanderKarpanProdege**
There are warnings in php 8.2 whenever a new property is added to a class dynamically:

```
class AspectPropertyValue
{
    public function __construct($noValueMessage = null, $value = "noValue")
    {
        if ($value !== "noValue") {
            $this->value = $value; // throws a warning
            // ...
        }
        // ...
    }
}
```

This PR declares the missing properties. The code is back-compatible with php 5.6

### CODE REVIEW

**Comment by Sara51D** [comment]
Thank you very much for your contribution @AlexanderKarpanProdege, we will look to review this in a couple of weeks and keep you updated.

**Comment by AlexanderKarpanProdege** [comment]
Thank you @Sara51D ! I'll be looking forward for the update.
The device detection library works great, but a single look up generates 850+ deprecation warnings in the logs on php 8.2. It'd be nice to get rid of those.

**Comment by AlexanderKarpanProdege** [comment]
Hello!
Did you have a chance to look at this PR?

**Comment by Sara51D** [comment]
Hi @AlexanderKarpanProdege, this is scheduled to be looked at in the second half of July as part of an overall refactoring of the CI/CD in PHP to make it simpler to process PRs. Thank you!

**Review by ben51degrees — APPROVED** [review]

**Comment by ben51degrees** [comment]
Hi @AlexanderKarpanProdege ,
Thanks for the contribution. I have reviewed and approved this PR.
Provided the tests all pass, this will be merged automatically this evening.
Thanks,
Ben

**Comment by ghost** [comment]
Hi @AlexanderKarpanProdege. As you can see, three of the tests failed, so the PR was not automatically merged. Are you able to review the PR to address these failures?
Kind regards,
Kirstin

**Comment by AlexanderKarpanProdege** [comment]
@kirstin51D I have accidentally closed this PR - this repo has changed its main branch from 'master' to 'main' and I wanted to do the same in my fork. I am going to create another PR.

A quick question - I've noticed in your updated CI file that you only test against PHP 8.0 - 8.2 
Does it mean this package only targets PHP 8+ ? Or PHP 7 and PHP 5.5-5.6 is still needed?

**Comment by Sara51D** [comment]
Hi @AlexanderKarpanProdege,
Thanks for the update, could you please advise when you plan to create the other PR?
Regarding your questions on versions - we want to support the versions that our customers are using, albeit within practical limits. To understand your question better, could you please share a little more detail around the question, what problem are you seeing around the versions?

**Comment by AlexanderKarpanProdege** [comment]
Hi @Sara51D ,
Thank you for reopening this PR - I'll finish it within the next few hours.

As for the different PHP versions: I deal with that a lot. Generally speaking, the more recent PHP version is used the shorter, more stable and reliable code can be written. Even if you drop PHP 5.6 here (which is barely used these days - see https://packagist.org/php-statistics - less than 0.5% worldwide), a null coalescing operator can be used to write, for example: 
`$this->minify = $settings["minify"] ?? true;` 
instead of 
`$this->minify = isset($settings["minify"]) ? $settings["minify"] : true;`

Also, this project uses a lot of what's called dynamically added class properties, which was okay in PHP 4, then considered an anti-pattern at the time of PHP 5, now it generates warnings in PHP 8.2 (affects the performance) and will be removed in PHP 8.3. The lack of warnings in the older versions of PHP hid the fact that this:
```php
$filter = new EvidenceKeyFilter();

$filter->filterEvidenceKey = function ($key) {
```
doesn't work, so you have bugs in `JavascriptBuilder.php` and `SequenceElement.php` which you are probably unaware of. (I think I'll fix it in this PR)

**Comment by AlexanderKarpanProdege** [comment]
The PR is ready. Tests pass for me locally. Please re-review it, otherwise ready to be merged.

**Comment by Sara51D** [comment]
Hi @AlexanderKarpanProdege , thank you for the PR.
Could we close this issue and start a new issue for the discussion on PHP versions here : https://github.com/51Degrees/device-detection-php/issues/10

**Pull request merged**
