### PR TITLE
Demo - do not merge! - Refactored the code

### PR DESCRIPTION
**Pull request by AlexanderKarpanProdege**
Hello,
Since I worked with the code in this project, I took several extra hours to rework it to meet the current standards of PHP source code. Maybe you could pick some ideas from here.
- I made PHP 7.1+ required in `composer.json`, added the required PHP extensions too;
- The code classes now follow PSR-4 for autoloading, the tests too;
- Fixed the code style and made it consistent through the project, the next step would be using a tool such as `phpcs` to enforce it;
- Updated the docblocks everywhere, modern IDEs use docblocks a lot to provide the autocompletion;
- Added a lot of type hints and return types, the code is more error-prone this way;
- Made many minor performance tweaks to save some CPU cycles;

I found a test which is conceptually broken - it passes but doesn't test what it claims it should test. I left a 'TODO' there.
I didn't touch the 'examples', only reformatted the code.

This can be a base for your next major release, if you want. In that case, the rest of your PHP repositories should be slightly updated because of the type hints and return types in these base classes.

Please feel free to close this PR.

### CODE REVIEW

**Comment by Sara51D** [comment]
Thank you very much for these inputs @AlexanderKarpanProdege we are going to go through these by the end of next week and keep you updated regarding the next steps.

**Comment by AlexanderKarpanProdege** [comment]
@Sara51D Do you mind if I close this PR? I keep getting daily emails about failed CI runs.

**Comment by justadreamer** [comment]
Hi @AlexanderKarpanProdege 

Just wanted to let you know that despite this PR has been closed - we've been drawing inspiration from it and have recently implemented these (and some other) pieces across all PHP repos:
- PSR-4 Autoloader
- removed unneeded submodule dependencies and strictly rely on composer
- strict treatment of warnings (the tests fail if there are any warnings detected deprecation or other)

The engineers continue to work on implementing the rest of the refactorings that you've done here - and we hope to bring more improvements in the upcoming months.  

Thank you for this PR once again.

**Comment by AlexanderKarpanProdege** [comment]
Дякую, @justadreamer ! :)
Дуже приємно. Радий, що мій код став у нагоді!
Звертайтесь, якщо потрібна допомога.

On a separate note, maybe you have or can create an empty 'database hash' file of a very small size? We'd like to include it in the repo to make the PHP extension happy in local and test environments. Perfectly fine if the answer is no.

**Comment by ghost** [comment]
Hi @AlexanderKarpanProdege! Is 139mb too big? We have a free "lite" hash data file: https://github.com/51Degrees/device-detection-data/blob/main/51Degrees-LiteV4.1.hash which contains a limited amount of properties. If this file is too big, let me know and I'll see what I can do.

**Comment by AlexanderKarpanProdege** [comment]
Hi @kirstin51D !
Yeah, unfortunately 139mb is too big. Our CI pipeline is triggered for every commit to run tests, that's 50-200 times a day, and we wouldn't want to download 139Mb every single time or include it in the code repository.

The thing is - while running tests we don't make any real lookups, so ideally we need a file which would be small but still valid. I have actually crafted one myself, 350 bytes - the extension loads it without errors but every lookup results in an error.

Of course, there are several other ways to work around that. For example, do not load the extension in tests and mock its functions. Also, I don't want to add more work to you guys. If that's hours of work - let's forget about it. Our current solution works reasonably well.

Thanks anyway! :)

**Comment by ghost** [comment]
I like it @AlexanderKarpanProdege! It's a good work around you've managed to create. Unfortunately it would be more than an hours work to create one our side, and we're not even sure if we could get the file down to as small as 350 bytes (or smaller). If your current file is small enough and works well enough, I think it might be best to stick with it. If that changes in future though, do reach out and we can raise a support ticket to look at it further :)

**Comment by AlexanderKarpanProdege** [comment]
Thank you and the team for the willing to help! :)

**Pull request closed without merging**
